### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SandraMadarnas** [4GeeksAcademy/sandrarodri_feed#1]
Feedback de Sandra:

¡Excelente, Sandra! Has realizado un buen trabajo, pero aún hay algunos detalles que debemos pulir para alcanzar la perfección.

Tal como te mencionó Adrián, al agregar una imagen diferente en términos de tamaño u orientación, se produce una ruptura en el diseño y el responsive no funciona correctamente. Además, el botón de "Ajustes" no se visualiza correctamente en la versión móvil.

Te animo a corregir estos detalles y entregar el proyecto nuevamente. Estoy segura de que con tu dedicación y esfuerzo lograrás un resultado impecable. ¡Ánimo y adelante!

Feedback Adrián:

Buen trabajo, pero vamos a necesitar algunos cambios:

Al poner un 40% de width a las cards rompes la vista de listado en la versión responsive. La app mejoraría quitando esa limitación. Además, la has puesto vía styles. Debemos evitar utilizar los styles siempre que sea posible (y aquí lo es).
La grid no funciona cuando las imágenes tienen diferentes tamaños. Asegúrate de que se muestren imágenes cuadradas independientemente del tamaño de la fuente.
Por favor, haz estos cambios y vuelve a entregar. Ánimo!

**Comment by srdgz** [comment]
Hola!
Ya he hecho las modificaciones que comentáis. Espero que ahora esté mejor! Si tengo que seguir modificando, ya me decís. Gracias!

**Comment by srdgz** [comment]
> Feedback de Sandra:
> 
> ¡Excelente, Sandra! Has realizado un buen trabajo, pero aún hay algunos detalles que debemos pulir para alcanzar la perfección.
> 
> Tal como te mencionó Adrián, al agregar una imagen diferente en términos de tamaño u orientación, se produce una ruptura en el diseño y el responsive no funciona correctamente. Además, el botón de "Ajustes" no se visualiza correctamente en la versión móvil.
> 
> Te animo a corregir estos detalles y entregar el proyecto nuevamente. Estoy segura de que con tu dedicación y esfuerzo lograrás un resultado impecable. ¡Ánimo y adelante!
> 
> Feedback Adrián:
> 
> Buen trabajo, pero vamos a necesitar algunos cambios:
> 
> Al poner un 40% de width a las cards rompes la vista de listado en la versión responsive. La app mejoraría quitando esa limitación. Además, la has puesto vía styles. Debemos evitar utilizar los styles siempre que sea posible (y aquí lo es). La grid no funciona cuando las imágenes tienen diferentes tamaños. Asegúrate de que se muestren imágenes cuadradas independientemente del tamaño de la fuente. Por favor, haz estos cambios y vuelve a entregar. Ánimo!

++++++++++++++++++++++++++++

Hola!
Ya he hecho las modificaciones que comentáis. Espero que ahora esté mejor! Si tengo que seguir modificando, ya me decís. Gracias!

**Comment by agarzon48** [comment]
Ahora está perfect! Enhorabuena! 😄
